"""Operator-facing helpers: first-run init and human review summaries."""

from __future__ import annotations

from pathlib import Path

from verisec_agent.models import Finding, ReviewReport, ValidationStep

_SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
}

DEFAULT_OPERATOR_CONFIG = """\
# VeriSec operator config (generated by `verisec init`)
# See docs/OPERATOR.md for day-to-day usage.

[review]
max_evidence_lines = 12
source_context_lines = 8
min_confidence = 0.35

[rules]
packs = ["builtin"]

[adapters]
paths = []

[policy]
enabled = true
execution_profile = "trusted-local"
allowed_adapters = [
  "pytest",
  "ruff",
  "semgrep",
  "codeql",
  "poc-script",
  "custom",
  "bandit",
  "pip-audit",
]
allowed_executables = ["{python}", "pytest", "ruff", "semgrep", "codeql", "bandit", "pip-audit"]
max_timeout_seconds = 600
max_output_bytes = 1000000
block_unavailable_adapters = false
warn_unavailable_adapters = true
environment_mode = "minimal"
network_access = "inherit"

[[verification.adapters]]
id = "pytest"
timeout_seconds = 60
required = false

[[verification.adapters]]
id = "ruff"
timeout_seconds = 60
required = false
"""


def init_project(
    *,
    target_dir: Path,
    force: bool = False,
) -> dict[str, object]:
    """Write a starter verisec.toml for local operator use."""
    root = target_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    config_path = root / "verisec.toml"
    created: list[str] = []
    skipped: list[str] = []

    if config_path.exists() and not force:
        skipped.append(str(config_path))
    else:
        config_path.write_text(DEFAULT_OPERATOR_CONFIG, encoding="utf-8")
        created.append(str(config_path))

    demo_diff = root / "examples" / "demo.diff"
    if demo_diff.is_file():
        review_step = (
            "python -m verisec_agent review "
            f'--diff "{demo_diff}" --repo "{root}" --out verisec-runs/demo'
        )
    else:
        review_step = (
            "python -m verisec_agent review "
            f'--diff path/to/change.diff --repo "{root}" --out verisec-runs/latest'
        )
    return {
        "target_dir": str(root),
        "config_path": str(config_path),
        "created": created,
        "skipped": skipped,
        "next_steps": [
            review_step,
            "Open the Markdown report under the --out directory (report.md)",
            "Optional: raise validation coverage via docs/VALIDATION_EVIDENCE.md",
            "Read docs/OPERATOR.md for PR review, CI gates, and next steps",
        ],
    }


def format_review_summary(report: ReviewReport) -> str:
    """Render a concise, first-time-friendly review summary for the terminal."""
    summary = report.summary
    finding_count = int(summary.get("finding_count", len(report.findings)))
    passed = int(summary.get("verification_passed", 0))
    total = int(summary.get("verification_count", len(report.verification)))
    covered = int(summary.get("validation_covered", 0))
    steps = int(summary.get("validation_step_count", len(report.validation_plan)))
    avg_conf = float(summary.get("avg_confidence", 0.0))
    bundle = Path(report.bundle_path)
    report_md = bundle / "report.md"
    report_sarif = bundle / "report.sarif"

    lines = [
        (
            f"VeriSec review complete: {finding_count} finding(s), "
            f"{passed}/{total} verification check(s) passed."
        ),
        f"Subject: {report.subject}",
        f"Bundle: {bundle}",
        f"Report: {report_md}",
        f"SARIF: {report_sarif}",
        (
            f"Validation coverage: {covered}/{steps} recommended checks covered"
            + (f"; avg confidence {avg_conf:.2f}" if finding_count else "")
        ),
        "",
    ]

    if report.findings:
        lines.append("Findings (highest severity first):")
        validation_by_finding = _validation_by_finding(report.validation_plan)
        ordered = sorted(
            report.findings,
            key=lambda item: (
                _SEVERITY_ORDER.get(item.severity, 99),
                -item.confidence,
                item.file_path,
                item.start_line,
            ),
        )
        for finding in ordered:
            lines.extend(
                _format_finding_lines(
                    finding,
                    validation_by_finding.get(finding.finding_id, ()),
                )
            )
        lines.append("")
    else:
        lines.extend(
            [
                "No security findings were generated.",
                "Common reasons:",
                "  - the diff has no Python (`.py` / `.pyi`) changes",
                "  - changes did not match current security rules",
                "  - confidence stayed below min_confidence in verisec.toml",
                "Open report.md for verification results and policy notes.",
                "",
            ]
        )

    lines.append("Next steps:")
    lines.append(f"  1. Open the full report: {report_md}")
    if report.findings:
        lines.append("  2. Review each finding's evidence, fix guidance, and validation gaps")
        lines.append(
            "  3. Raise validation coverage with VERISEC_EVIDENCE markers "
            "(docs/VALIDATION_EVIDENCE.md)"
        )
        lines.append(
            "  4. Optional PR comment: "
            "python -m verisec_agent pr-comment "
            f"--report {bundle / 'report.json'} --out verisec-runs/pr-comment.md"
        )
        lines.append(f"  5. Optional code-scanning upload: use {report_sarif}")
    else:
        lines.append("  2. If you expected findings, try a demo: "
                     "python -m verisec_agent review --diff examples/demo.diff --repo .")
        lines.append("  3. List adapters: python -m verisec_agent tools")
    lines.append(
        f"  Replay verification later: "
        f"python -m verisec_agent replay --bundle {bundle} --repo ."
    )
    lines.append("  Operator guide: docs/OPERATOR.md")
    return "\n".join(lines) + "\n"


def format_init_summary(result: dict[str, object]) -> str:
    lines = ["VeriSec operator init complete.", f"Directory: {result['target_dir']}"]
    created = list(result.get("created") or [])
    skipped = list(result.get("skipped") or [])
    if created:
        lines.append("Created:")
        lines.extend(f"  - {path}" for path in created)
    if skipped:
        lines.append("Already present (use --force to overwrite):")
        lines.extend(f"  - {path}" for path in skipped)
    lines.append("")
    lines.append("Next steps:")
    for index, step in enumerate(result.get("next_steps") or [], start=1):
        lines.append(f"  {index}. {step}")
    return "\n".join(lines) + "\n"


def _format_finding_lines(
    finding: Finding,
    steps: tuple[ValidationStep, ...],
) -> list[str]:
    location = f"{finding.file_path}:{finding.start_line}-{finding.end_line}"
    lines = [
        (
            f"  [{finding.severity}] {finding.rule_id}  {location}  "
            f"confidence={finding.confidence:.2f}"
        ),
        f"    {finding.title}",
    ]
    if finding.analysis_scope or finding.analysis_notes:
        mode = _extract_note_field(finding.analysis_notes, "Mode")
        family = _extract_note_field(finding.analysis_notes, "Family")
        bits = []
        if family:
            bits.append(f"family={family}")
        if mode:
            bits.append(f"mode={mode}")
        if finding.analysis_scope:
            bits.append(f"scope={finding.analysis_scope}")
        if bits:
            lines.append(f"    ({', '.join(bits)})")
    if finding.fix_guidance:
        lines.append(f"    Fix: {finding.fix_guidance}")
    missing = [step.recommended_check for step in steps if step.status == "missing"]
    covered = [step.recommended_check for step in steps if step.status == "covered"]
    if covered:
        lines.append(f"    Validated: {'; '.join(covered)}")
    if missing:
        lines.append(f"    Still missing validation: {'; '.join(missing)}")
    elif finding.recommended_validation and not steps:
        lines.append(
            "    Suggested validation: " + "; ".join(finding.recommended_validation)
        )
    return lines


def _validation_by_finding(
    validation_plan: tuple[ValidationStep, ...],
) -> dict[str, tuple[ValidationStep, ...]]:
    grouped: dict[str, list[ValidationStep]] = {}
    for step in validation_plan:
        grouped.setdefault(step.finding_id, []).append(step)
    return {key: tuple(value) for key, value in grouped.items()}


def _extract_note_field(notes: str, label: str) -> str:
    prefix = f"{label}: "
    for part in notes.split("."):
        text = part.strip()
        if text.startswith(prefix):
            return text.removeprefix(prefix).strip()
    return ""
